apiVersion: v1
kind: Service
metadata: 
  name: lucas-service
spec:
  type: ExternalName
  externalName: lucas.dev
  selector:
    app:  api
  ports:
  - protocol:  TCP
    port:  80
    targetPort:  8080